CREATE DATABASE Mail

CREATE TABLE  "USER"
   (	
	ID int IDENTITY(1,1) PRIMARY KEY, 
	NAME NVARCHAR(200) NOT NULL, 
	EMAIL NVARCHAR(200) UNIQUE NOT NULL, 
	PASSWORD NVARCHAR(200) NOT NULL, 
	GENDER NVARCHAR(100) NOT NULL, 
	DOB DATE NOT NULL, 
	ADDRESSLINE NVARCHAR(1000) NOT NULL, 
	CITY NVARCHAR(200), 
	STATE NVARCHAR(200), 
	COUNTRY NVARCHAR(200), 
	CONTACT NVARCHAR(300), 
	REGISTEREDDATE DATE
   )


CREATE TABLE  "MESSAGE" 
   (	
	ID int IDENTITY(1,1) PRIMARY KEY, 
	SENDER NVARCHAR(4000) NOT NULL, 
	RECEIVER NVARCHAR(4000) , 
	SUBJECT NVARCHAR(4000), 
	MESSAGE NVARCHAR(4000), 
	TRASH NVARCHAR(4000) , 
	MESSAGEDATE DATE NOT NULL, 
   );


   SELECT * FROM dbo."USER"
